Models/Usina.cs
using Engie.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Engie.Models
{
    public class Usina
    {
        public int Id { get; set; }
        [Required]
        public string Uc { get; set; }
        [Required]
        public bool Ativo { get; set; }
        [Required]
        public int IdFornecedor { get; set; }       
        public List<Fornecedor> Fornecedor { get; set; }

        private readonly Context _context = new Context();
        public List<Fornecedor> TodosFornecedores()
        {            
            return _context.Fornecedor.OrderBy(x => x.Id).ToList();
        }
        public List<Usina> PegarTodos()
        {
            return _context.Usina.OrderBy(x => x.IdFornecedor).ToList();
        }
    }
}

Controllers/UsinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Engie.Data;
using Engie.Models;

namespace Engie.Controllers
{
    public class UsinasController : Controller
    {
        private Context db = new Context();

        // GET: Usinas
        public ActionResult Index()
        {
            //Recupera variaveis da URL
            int fornParam = Convert.ToInt32(Request.QueryString["fornecedorDrop"]);
            int ativoParam = Convert.ToInt32(Request.QueryString["AtivoDrop"]);

            //construtor do objeto Usina
            Usina usina = new Usina();

            //Recupera lista de usinas
            var todasUsinas = usina.PegarTodos();

            //recupera lista de fornecedores
            var fornecedor = db.Fornecedor.ToList();
            
            //Construto do dropdownlist de filtros
            List<SelectListItem> estadoList = new List<SelectListItem>();
            List<SelectListItem> fornecedorList = new List<SelectListItem>();

            //Adição de opção basicas do filtro para o dropdownlist  
            estadoList.Add(new SelectListItem { Text = "Todos", Value = "0" });
            estadoList.Add(new SelectListItem { Text = "Sim", Value = "1" });
            estadoList.Add(new SelectListItem { Text = "Não", Value = "2" });
            fornecedorList.Add(new SelectListItem { Text = "Todos", Value = "0" });

            //Adiciona registro de fornecedores ao objeto do dropdownlist
            foreach (var item in fornecedor)
            {
                fornecedorList.Add(new SelectListItem { Text = item.Nome, Value = item.Id.ToString() });
            }

            //contrutor do objeto que vai com todas as propriedades dos objetos Usinas e seu Fornecedor preenchidas para popultar table
            List<Usina> UsinaCompleta = new List<Usina>();

            //construtor do objeto auxiliador
            List<Fornecedor> fornecedores = new List<Fornecedor>();

            //populando tabela
            //filtros: Se ddl de fornecedor diferente de todos e ativo igual a todos
            if (fornParam > 0 && ativoParam == 0)
            {
                UsinaCompleta.Clear();
                       
                bool? a = ativoParam == 0 ? true : false;
                foreach (var item in todasUsinas.Where(x => x.IdFornecedor == fornParam))
                {
                    foreach (var item2 in fornecedor)
                    {
                        if (item.IdFornecedor == item2.Id)
                        {
                            var retFornecedor = fornecedor.Where(x => x.Id == item.IdFornecedor).ToList();
                            UsinaCompleta.Add(new Usina { Id = item.Id, Ativo = item.Ativo, Uc = item.Uc, IdFornecedor = item.IdFornecedor, Fornecedor = retFornecedor });
                        }
                    }
                }
            }
            //filtrps: se ddl igual a todos e ativo diferente de todos
            else if (fornParam == 0 && ativoParam > 0)
            {
                UsinaCompleta.Clear();
                //Filtros           
                bool? a = ativoParam == 1 ? true : false;
                foreach (var item in todasUsinas.Where(x => x.Ativo.Equals(a)))
                {
                    foreach (var item2 in fornecedor)
                    {
                        if (item.IdFornecedor == item2.Id)
                        {
                            var retFornecedor = fornecedor.Where(x => x.Id == item.IdFornecedor).ToList();
                            UsinaCompleta.Add(new Usina { Id = item.Id, Ativo = item.Ativo, Uc = item.Uc, IdFornecedor = item.IdFornecedor, Fornecedor = retFornecedor });
                        }
                    }
                }
            }
            //filtros: se ambos filtros estiverem diferente de todos
            else if (fornParam > 0 && ativoParam > 0)
            {
                UsinaCompleta.Clear();
                //Filtros           
                bool? a = ativoParam == 0 ? true : false;
                foreach (var item in todasUsinas.Where(x => x.IdFornecedor == fornParam && x.Ativo.Equals(a)))
                {
                    foreach (var item2 in fornecedor)
                    {
                        if (item.IdFornecedor == item2.Id)
                        {
                            var retFornecedor = fornecedor.Where(x => x.Id == item.IdFornecedor).ToList();
                            UsinaCompleta.Add(new Usina { Id = item.Id, Ativo = item.Ativo, Uc = item.Uc, IdFornecedor = item.IdFornecedor, Fornecedor = retFornecedor });
                        }
                    }
                }
            }
            //Carregamento padrao da tabela
            else 
            {
                UsinaCompleta.Clear();
                foreach (var item in todasUsinas)
                {
                    foreach (var item2 in fornecedor)
                    {
                        if (item.IdFornecedor == item2.Id)
                        {
                            var retFornecedor = fornecedor.Where(x => x.Id == item.IdFornecedor).ToList();
                            UsinaCompleta.Add(new Usina { Id = item.Id, Ativo = item.Ativo, Uc = item.Uc, IdFornecedor = item.IdFornecedor, Fornecedor = retFornecedor });
                        }
                    }
                }
            }

            //Auxiliar para o drop
            ViewBag.fornecedorDrop = fornecedorList.ToList();
            ViewBag.AtivoDrop = estadoList.ToList();

            return View(UsinaCompleta);
        }

        // GET: Usinas/Create
        public ActionResult Create()
        {
            //contrutores dos objetos
            Fornecedor fornecedor = new Fornecedor();
            Usina usina = new Usina();

            //carrega drop de fornecedores
            usina.Fornecedor = usina.TodosFornecedores();
            ViewData["Fornecedor"] = db.Fornecedor;

            ViewData["Erro"] = "";
            //seta checkbox ativo chekcado
            usina.Ativo = true;
            return View(usina);
        }

        // POST: Usinas/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Uc,Ativo,IdFornecedor")] Usina usina)
        {
            //verifica se dados sao validos
            if (ModelState.IsValid)
            {
                //verifica se existe uc e fornecedor cadastradao                                               
                var cadastrado = db.Usina.Where(x => x.Uc == usina.Uc && x.IdFornecedor == usina.IdFornecedor).ToList();
                //não há registro com mesmos dados de uc e fornecedor
                if (cadastrado.Count() == 0)
                {
                    //Adiciona objeto usina no banco
                    db.Usina.Add(usina);
                    //confirmação
                    db.SaveChanges();
                    //mensagem de confirmação
                    ModelState.AddModelError("CustomError", "Castro Realizado!");
                }
                //registro igual encontrado 
                else
                {
                    //mensagem de erro
                    string errorMessage = String.Format("Cadastro existente!");
                    ModelState.AddModelError(string.Empty, errorMessage);
                }
            }
            //Carrega drop fornecedores
            usina.Fornecedor = usina.TodosFornecedores();
            ViewData["Fornecedor"] = db.Fornecedor;

            return View(usina);
        }

        // GET: Usinas/Edit/5
        public ActionResult Edit(int? id)
        {
            //verifica retorno do id
            if (id == null)
            {
                //Erro
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //busca registro do id no banco
            Usina usinaID = db.Usina.Find(id);

            //verifica se existe o registro no banco
            if (usinaID == null)
            {
                return HttpNotFound();
            }

            //busca de fornecedores
            var retFornecedor = db.Fornecedor.ToList();
            //verifica fornecedor com mesmo ID do objeto Usina
            var retFornecedoriD = retFornecedor.Where(x => x.Id == id).ToList();
            //Seta o fornecedor com todas propriedades no objeto usina
            usinaID.Fornecedor = retFornecedoriD;
            
            //Auxilicar para carregar o drop de fornecedores
            ViewData["Fornecedor"] = retFornecedor.ToList();

           //Recupera nome do fornecedor para carregar drop com o nome           
            foreach (var item in retFornecedor)
            {
                ViewData["FornecedorId"] = item.Nome;
            }

            return View(usinaID);
        }

        // POST: Usinas/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Uc,Ativo,IdFornecedor")] Usina usina)
        {
            //verifica se os dados sao validos
            if (ModelState.IsValid)
            {
                //verifica se existe usina com os mesmo dados cadastrado no banco
                var cadastrado = db.Usina.Where(x => x.Uc == usina.Uc && x.IdFornecedor == usina.IdFornecedor && x.Ativo == usina.Ativo).ToList();
                //se houver alteração de dados, faz edição do registro usina

Views/Usinas/Create.cshtml
@model Engie.Models.Usina

@{
    ViewBag.Title = "Create";
}

<h5 class="mt-5">Cadastro de usinas</h5>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*MENSAGENS DE SUCESSO/ERRO*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.ValidationMessage("CustomError", new { @class = "text-success" })
        <div class="form-inline form-group ">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        @*FORMULARIO DE CADASTRO*@
        <div class="form-inline form-group">
            @Html.Label("Forrnecedor*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdFornecedor, new SelectList(Model.Fornecedor, "Id", "Nome"), "Selecione",new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.IdFornecedor, "", new { @class = "msg text-danger" })
            </div>
        </div>
        <div class="form-inline form-group">
            @Html.Label("Uc da Usina*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uc, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">                     
            <div class="row">
                <div class="form-inline" style="margin-left:70%">
                    <input type="submit" value="Salvar" class="btn btn-success mr-2 " />                 
                    @Html.ActionLink("Fechar", "Index",null, new { @class = "btn btn-danger mr-2" })
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Usinas/Delete.cshtml
@model Engie.Models.Usina

@{
    ViewBag.Title = "Delete";
}

<h5 class="mt-5">Exclusão de Usina</h5>
<hr />
<div>   @*DETALHES DO REGISTRO A SER EXCLUIDO*@
    <div class="form-horizontal">
        <div class="form-inline form-group ">
            @Html.DisplayNameFor(model => model.Ativo)
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.DisplayFor(model => model.Ativo)
                </div>
            </div>
        </div>
        <div class="form-inline form-group">
            @Html.DisplayName("Fornecedor*")
            <div class="col-md-10">
                @Html.DisplayFor(model => model.IdFornecedor)
            </div>
        </div>
        <div class="form-inline form-group">
            @Html.DisplayName("Uc da usina*")
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Uc)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
            </div>
            <div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-inline" style="margin-left:70%">
                        <input type="submit" value="Deletar" class="btn btn-success mr-2" />
                        @Html.ActionLink("Fechar", "Index", null, new { @class = "btn btn-danger mr-2" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Views/Usinas/Edit.cshtml
@model Engie.Models.Usina

@{
    ViewBag.Title = "Edit";
}

    <h5 class="mt-5">Edição de Usinas</h5>
    <hr />
@*FOMULARIO DE EDIÇÃO*@
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @*MENSAGENS DE SUCESSO/ERRO*@
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.ValidationMessage("CustomError", new { @class = "text-success" })
            @Html.HiddenFor(model => model.Id)
            @*FORMULARIOS*@
            <div class="form-inline form-group ">
                @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Ativo)
                        @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-inline form-group">
                @Html.Label("Forrnecedor*", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IdFornecedor, new SelectList(Model.TodosFornecedores(), "Id", "Nome"), null,new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.IdFornecedor, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-inline form-group">
                @Html.Label("Uc da Usina*", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Uc, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Uc, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                </div>
                <div>
                </div>
                <div class="row">
                    <div class="form-inline" style="margin-left:70%">
                        <input type="submit" value="Salvar" class="btn btn-success mr-2" />
                        @Html.ActionLink("Fechar", "Index", null, new { @class = "btn btn-danger mr-2" })
                    </div>
                </div>
            </div>
        </div>
    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Usinas/Index.cshtml
@model IEnumerable<Engie.Models.Usina>

@{
    ViewBag.Title = "Index";
}
<h5 class="mt-5">Listagem de usinas de Geração Distribuída</h5>
<hr />
@using (Html.BeginForm("Index", "Usinas", FormMethod.Get))
{/*FILTTROS*/
    <div class="row">
        <div class="col-md-6">
            <div class="form-inline">
                <p class="mt-2 mr-1">Fornecedor</p>
                @Html.DropDownList("fornecedorDrop", null, null, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                <p class="mt-2 mr-1">Ativo</p>
                @Html.DropDownList("AtivoDrop", null, null, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="form-inline" style="margin-left:70%">
            @Html.ActionLink("Cadastrar", "Create", null, new { @class = "btn btn-success mr-2" })
            <input type="submit" value="Filtrar" class="btn btn-success " />
        </div>
    </div>
}
@*TABELA DE USINAS*@
<table class="table mt-5">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Fornecedor")
            </th>
            <th>
                @Html.DisplayName("UC da Usina")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>

            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>@*FOREACH PARA PEGAR VALOR DO NOME PROPRIEDADE DA SUBCLASE NA SUPERCLASE *@
                @foreach (var itemForncedor in item.Fornecedor)
                {
                    <td>
                        @Html.DisplayFor(m => itemForncedor.Nome)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Uc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>